/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-23 22:35:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Construction Xpert - Home</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Custom background image styling with overlay */\r\n");
      out.write("        .hero-bg {\r\n");
      out.write("            background-image: url('/construction-xpert/images/construction-hero.jpg');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-bg::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background-color: rgba(16, 64, 43, 0.7); /* Dark green overlay */\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"font-sans bg-gray-50\">\r\n");
      out.write("<!-- Header and Navigation -->\r\n");
      out.write("<nav class=\"bg-green-800 text-white\">\r\n");
      out.write("    <div class=\"container mx-auto px-6 py-4 flex justify-between items-center\">\r\n");
      out.write("        <div class=\"flex items-center\">\r\n");
      out.write("            <div class=\"w-10 h-10 bg-white rounded-md flex items-center justify-center mr-2\">\r\n");
      out.write("                <div class=\"w-6 h-6 border-2 border-green-800\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"text-sm font-bold\">CONSTRUCTION</div>\r\n");
      out.write("                <div class=\"text-sm font-bold\">XPERT</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"hidden md:flex space-x-6\">\r\n");
      out.write("            <li><a href=\"#\" class=\"hover:text-green-300 font-medium\">HOME</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"hover:text-green-300 font-medium\">PROJECTS</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"hover:text-green-300 font-medium\">TASKS</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"hover:text-green-300 font-medium\">RESOURCES</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"hover:text-green-300 font-medium\">CONTACT</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <button class=\"md:hidden\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section with Image -->\r\n");
      out.write("<header class=\"hero-bg relative py-32\">\r\n");
      out.write("    <div class=\"hero-content container mx-auto px-6\">\r\n");
      out.write("        <div class=\"max-w-xl text-white\">\r\n");
      out.write("            <h1 class=\"text-5xl font-bold mb-2\">Construction.</h1>\r\n");
      out.write("            <h1 class=\"text-5xl font-bold mb-6\">Redefined.</h1>\r\n");
      out.write("            <p class=\"text-xl mb-8\">Plan it. Track it. Build it. All in one powerful platform designed for builders like you.</p>\r\n");
      out.write("            <a href=\"#features\" class=\"inline-block bg-green-500 hover:bg-green-600 text-white font-semibold py-3 px-8 rounded-lg shadow-lg transition duration-300\">\r\n");
      out.write("                DISCOVER MORE\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Features Section -->\r\n");
      out.write("<section id=\"features\" class=\"container mx-auto px-6 py-20\">\r\n");
      out.write("    <div class=\"text-center mb-16\">\r\n");
      out.write("        <h2 class=\"text-4xl font-bold text-gray-800 mb-4\">Master Your Construction Projects</h2>\r\n");
      out.write("        <q class=\"text-lg text-gray-600 max-w-3xl mx-auto\">\r\n");
      out.write("            Take control of every detail in your projects.\r\n");
      out.write("        </q>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"grid grid-cols-1 md:grid-cols-3 gap-8 mb-16\">\r\n");
      out.write("        <!-- Projects Card -->\r\n");
      out.write("        <div class=\"bg-white p-8 rounded-lg shadow-xl border-t-4 border-green-600 hover:shadow-2xl transition duration-300\">\r\n");
      out.write("            <h3 class=\"text-2xl font-semibold text-gray-800 mb-3\">Projects</h3>\r\n");
      out.write("            <p class=\"text-gray-600 mb-4\">Launch and manage your construction projects with precision and confidence.</p>\r\n");
      out.write("            <a href=\"projet\" class=\"text-green-600 hover:text-green-800 font-medium flex items-center\">\r\n");
      out.write("                Go to Projects\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-4 w-4 ml-1\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\" />\r\n");
      out.write("                </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tasks Card -->\r\n");
      out.write("        <div class=\"bg-white p-8 rounded-lg shadow-xl border-t-4 border-green-600 hover:shadow-2xl transition duration-300\">\r\n");
      out.write("            <h3 class=\"text-2xl font-semibold text-gray-800 mb-3\">Tasks</h3>\r\n");
      out.write("            <p class=\"text-gray-600 mb-4\">Stay on top of every task, from planning to completion, with our intuitive tracking system.</p>\r\n");
      out.write("            <a href=\"tache?projetId=1\" class=\"text-green-600 hover:text-green-800 font-medium flex items-center\">\r\n");
      out.write("                View Tasks\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-4 w-4 ml-1\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\" />\r\n");
      out.write("                </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Resources Card -->\r\n");
      out.write("        <div class=\"bg-white p-8 rounded-lg shadow-xl border-t-4 border-green-600 hover:shadow-2xl transition duration-300\">\r\n");
      out.write("            <h3 class=\"text-2xl font-semibold text-gray-800 mb-3\">Resources</h3>\r\n");
      out.write("            <p class=\"text-gray-600 mb-4\">Track materials, equipment, and suppliers effortlessly to optimize your resource allocation.</p>\r\n");
      out.write("            <a href=\"ressource\" class=\"text-green-600 hover:text-green-800 font-medium flex items-center\">\r\n");
      out.write("                Manage Resources\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-4 w-4 ml-1\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\" />\r\n");
      out.write("                </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Call to Action -->\r\n");
      out.write("<section class=\"bg-green-100 py-16\">\r\n");
      out.write("    <div class=\"container mx-auto px-6 text-center\">\r\n");
      out.write("        <h2 class=\"text-3xl font-bold text-gray-800 mb-4\">Ready to Build Smarter?</h2>\r\n");
      out.write("        <p class=\"text-lg text-gray-600 mb-8 max-w-2xl mx-auto\">Join Construction Xpert today and transform the way you manage construction projects.</p>\r\n");
      out.write("        <a href=\"projet\" class=\"inline-block bg-green-600 hover:bg-green-800 text-white font-semibold py-3 px-10 rounded-lg shadow-lg transition duration-300\">\r\n");
      out.write("            GET STARTED NOW\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-green-800 text-white py-8\">\r\n");
      out.write("    <div class=\"container mx-auto px-6\">\r\n");
      out.write("        <div class=\"flex flex-col md:flex-row justify-between items-center\">\r\n");
      out.write("            <div class=\"flex items-center mb-4 md:mb-0\">\r\n");
      out.write("                <div class=\"w-8 h-8 bg-white rounded-md flex items-center justify-center mr-2\">\r\n");
      out.write("                    <div class=\"w-5 h-5 border-2 border-green-800\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"font-bold\">CONSTRUCTION XPERT</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text-sm\">\r\n");
      out.write("                Â© 2025 Construction Xpert. All rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
